In [1]:
import torch 
import numpy as np 
from torchvision import datasets, transforms 

### Playing around with some `Pytorch` features

1) Tensors  
  
Pytorch tensors are basically numpy arrays but work on GPUs

In [8]:
tensor = torch.rand(4, 4)
print(tensor)
print(tensor[:,0]) # first column (same as numpy)
print(tensor[0,:]) # first row
tensor[...,:-1] = 0. # changes all rows up to the last row to be zero
print(tensor)

tensor([[0.7176, 0.9758, 0.2720, 0.1525],
        [0.2911, 0.4558, 0.5363, 0.2496],
        [0.8435, 0.8710, 0.2288, 0.9301],
        [0.1482, 0.1637, 0.0110, 0.7476]])
tensor([0.7176, 0.2911, 0.8435, 0.1482])
tensor([0.7176, 0.9758, 0.2720, 0.1525])
tensor([[0.0000, 0.0000, 0.0000, 0.1525],
        [0.0000, 0.0000, 0.0000, 0.2496],
        [0.0000, 0.0000, 0.0000, 0.9301],
        [0.0000, 0.0000, 0.0000, 0.7476]])


In [ ]:
transform = transforms.Compose([
    transforms.ToTensor(),  # Convert images to PyTorch tensors
    transforms.Normalize((0.5,), (0.5,))  # Normalize the images to [-1, 1]
])

In [ ]:
train_dataset = datasets.MNIST(
    root='./data',  # Directory where data will be stored
    train=True,     # Download the training set
    transform=transform,  # Apply the transform
    download=True   # Download the data if not already available
)

# Download and load the test dataset
test_dataset = datasets.MNIST(
    root='./data',
    train=False,
    transform=transform,
    download=True
)
